version: "2"
services:
  orthanc:
    image: orthancteam/orthanc
    ports: ["8042:8042"]
    volumes: ["orthanc-storage:/var/lib/orthanc/db"]
    environment:
      VERBOSE_STARTUP: "true"
      #VERBOSE_ENABLED: "true"

      # you must enable the StoneViewer and the DicomWeb plugins
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"

      ORTHANC__DICOM_WEB__SERIES_METADATA: "Full"
      ORTHANC__DICOM_WEB__STUDIES_METADATA: "Full"
      ORTHANC__DICOM_WEB__METADATA_WORKER_THREADS_COUNT : "4"

      # if you want to work in "MainDicomTags" mode for the metadata, you should define
      # these extra main dicomtags
      # ORTHANC__EXTRA_MAIN_DICOM_TAGS: |
      #   {
      #     "Instance" : [
      #         "Rows",
      #         "Columns",
      #         "ImageType",
      #         "SOPClassUID",
      #         "ContentDate",
      #         "ContentTime",
      #         "FrameOfReferenceUID",
      #         "PixelSpacing",
      #         "SpecificCharacterSet",
      #         "BitsAllocated",
      #         "BitsStored",

      #         "RescaleSlope",
      #         "RescaleIntercept",
      #         "SliceThickness",
      #         "WindowCenter",
      #         "WindowWidth",
      #         "PhotometricInterpretation",
      #         "PixelRepresentation"
      #     ],
      #     "Series" : [
      #         "TimezoneOffsetFromUTC",
      #         "PerformedProcedureStepStartDate",
      #         "PerformedProcedureStepStartTime",
      #         "RequestAttributesSequence"
      #     ],
      #     "Study": [
      #         "TimezoneOffsetFromUTC"
      #     ],
      #     "Patient": []
      #     }

      # StoneViewer configurations
      ORTHANC__STONE_WEB_VIEWER__DATE_FORMAT: "DD/MM/YYYY"

      ORTHANC__AUTHENTICATION_ENABLED: "false"
volumes:
  orthanc-storage:
