version: "2"
services:
  orthanc-dicom:
    image: orthancteam/orthanc
    depends_on: [index]
    ports: ["104:4242"]
    volumes: ["storage:/var/lib/orthanc/db"]
    environment:
      ORTHANC__NAME: "Orthanc DICOM"
      ORTHANC__POSTGRESQL__HOST: "index"
    restart: unless-stopped

  nginx-load-balancer:
    build: nginx
    depends_on: [orthanc-http-a, orthanc-http-b]
    restart: unless-stopped
    ports: ["80:80"]

  orthanc-http-a:
    image: orthancteam/orthanc
    depends_on: [index]
    volumes: ["storage:/var/lib/orthanc/db"]
    environment:
      ORTHANC__NAME: "Orthanc HTTP A"
      ORTHANC__POSTGRESQL__HOST: "index"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      ORTHANC__SAVE_JOBS: "false"
      ORTHANC__REGISTERED_USERS: |
        {"demo": "demo"}
    restart: unless-stopped

  orthanc-http-b:
    image: orthancteam/orthanc
    depends_on: [index]
    volumes: ["storage:/var/lib/orthanc/db"]
    environment:
      ORTHANC__NAME: "Orthanc HTTP B"
      ORTHANC__POSTGRESQL__HOST: "index"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      ORTHANC__SAVE_JOBS: "false"
      ORTHANC__REGISTERED_USERS: |
        {"demo": "demo"}
    restart: unless-stopped

  index:
    image: postgres
    volumes: ["index:/var/lib/postgresql/data"]
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
volumes:
  storage:
  index:
