version: "2"
services:
  orthanc-under-tests:
    build: orthanc-under-tests
    depends_on:
      - odbc-pg-server
    environment:
      # ORTHANC__ODBC__INDEX_CONNECTION_STRING: "Driver={PostgreSQL};Server=pg;Port=5432;Database=postgres;Uid=postgres;Pwd=postgres;"
      ORTHANC__ODBC__INDEX_CONNECTION_STRING: "DSN=postgres"
      ORTHANC__ODBC__STORAGE_CONNECTION_STRING: "DSN=postgres"
      ORTHANC__ODBC__ENABLE_INDEX: "true"
      ORTHANC__ODBC__ENABLE_STORAGE: "true"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"

  orthanc-tests:
    build: orthanc-tests
    depends_on:
      - orthanc-under-tests

  odbc-pg-server:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
