version: "3.3"

services:
    orthanc:
        image: osimis/orthanc
        ports: [8042:8042]
        environment:
            - ORTHANC__AZURE_BLOB_STORAGE__CONTAINER_NAME=testcontainer

            - ORTHANC__AUTHENTICATION_ENABLED=false
            - ORTHANC__DICOM_SERVER_ENABLED=false

        secrets:
          - ORTHANC__AZURE_BLOB_STORAGE__CONNECTION_STRING
secrets:
  ORTHANC__AZURE_BLOB_STORAGE__CONNECTION_STRING:
    file: blob-connection-string.txt
  # ORTHANC__MSSQL__CONNECTION_STRING:
  #   file: mssql-connection-string.txt
